package rigs

const (
	CAT_DIR_UP = iota
	CAT_DIR_DOWN
)

const (
	RIG_GET = "GET"
	RIG_SET = "SET"
	RIG_RSP = "RSP"

)

const (
	PRM_VFOA = "VFOA"
	PRM_VFOB = "VFOB"
	PRM_CLAR = "CLAR"
	PRM_MODUL = "MODUL"
	PRM_MODE  = "MODE"
	PRM_FILT = "FILTER"
	PRM_TXVFO = "TXVFO"
	PRM_SPLIT = "SPLIT"
	PRM_SMETER = "SMETER"
	PRM_SWR = "SWR"
	PRM_COMP = "COMP"
	PRM_ALC = "ALC"
	PRM_POWER = "POWER"
	PRM_ID = "ID"
	PRM_VDD = "VDD"
	PRM_AUDIOG = "AUDIOG"
	PRM_TUNER = "TUNER"
	PRM_ATT = "ATT"
	PRM_PREAMP = "PREAMP"
	PRM_NBSTATUS = "NBSTATUS"
	PRM_NBLEVEL = "NBLEVEL"
	PRM_NRLVEL = "NRLEVEL"
	PRM_RFGAIN = "RFGAIN"
	PRM_PWRSWITCH = "PWRSWITCH"
	PRM_VOX = "VOX"

	PRM_KEYSPEED = "KEYSPEED"
	PRM_AUTOINFO = "AUTOINFO"

)

const (
	VAL_ON = "ON"
	VAL_OFF = "OFF"
	VAL_VFOA = "VFOA"
	VAL_VFOB = "VFOB"
)

const (
	MODUL_USB = "USB"
	MODUL_LSB = "LSB"
	MODUL_CW = "CW"
	MODUL_CW_R = "CW_R"
	MODUL_AM = "AM"
	MODUL_FM = "FW"
	MODUL_C4FM = "C4FM"
)
// Transmission mode
const (
	MODE_DATA = "DATA"
	MODE_RTTY = "RTTY"
	MODE_VOICE = "VOICE"
)
// Filter
const (
	FILT_N = "NARROW"
	FILT_W = "WIDE"
)

