streams:
   - name : ser2net
     modules :
       - name     : "pipe"
         module   : "pipe"
         config :
           tap  : "false"
       - name     : "serial"
         module   : "serial"
         upstream : "pipe"
         config    :
            port   : "/dev/tty.SLAB_USBtoUART"
            baud   : "38400"
            parity : "N"
            data_bits   : "8"
            stop_bits   : "1"
            rts_cts     : "false"
       - name     : "net"
         module   : "tcp_server"
         upstream : "pipe"
         config  :
            address : ":7375"
